name: David Lebrun
description: Blogging about computer software and security
meta_description: "My blog built with <3"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://davidlebrun.ca'
google_analytics: 'UA-41441510-1'
disqus: true
disqus_shortname: 'davidlebrun'

# Details for the RSS feed generator
url:            'http://davidlebrun.ca'
author:         'David Lebrun'
authorTwitter:  'davidlebr1'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
